// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/vault/vault.proto

package vault

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSecretRequest) Reset() {
	*x = ReadSecretRequest{}
	mi := &file_proto_vault_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSecretRequest) ProtoMessage() {}

func (x *ReadSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSecretRequest.ProtoReflect.Descriptor instead.
func (*ReadSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{0}
}

func (x *ReadSecretRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Renewable     bool                   `protobuf:"varint,3,opt,name=renewable,proto3" json:"renewable,omitempty"`
	LeaseDuration int32                  `protobuf:"varint,4,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSecretResponse) Reset() {
	*x = ReadSecretResponse{}
	mi := &file_proto_vault_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSecretResponse) ProtoMessage() {}

func (x *ReadSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSecretResponse.ProtoReflect.Descriptor instead.
func (*ReadSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{1}
}

func (x *ReadSecretResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReadSecretResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ReadSecretResponse) GetRenewable() bool {
	if x != nil {
		return x.Renewable
	}
	return false
}

func (x *ReadSecretResponse) GetLeaseDuration() int32 {
	if x != nil {
		return x.LeaseDuration
	}
	return 0
}

func (x *ReadSecretResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSecretRequest) Reset() {
	*x = WriteSecretRequest{}
	mi := &file_proto_vault_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSecretRequest) ProtoMessage() {}

func (x *WriteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSecretRequest.ProtoReflect.Descriptor instead.
func (*WriteSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{2}
}

func (x *WriteSecretRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteSecretRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteSecretResponse) Reset() {
	*x = WriteSecretResponse{}
	mi := &file_proto_vault_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteSecretResponse) ProtoMessage() {}

func (x *WriteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteSecretResponse.ProtoReflect.Descriptor instead.
func (*WriteSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{3}
}

func (x *WriteSecretResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_proto_vault_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{4}
}

func (x *ListSecretsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_proto_vault_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{5}
}

func (x *ListSecretsResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_proto_vault_vault_proto protoreflect.FileDescriptor

const file_proto_vault_vault_proto_rawDesc = "" +
	"\n" +
	"\x17proto/vault/vault.proto\x12\fsecret_proto\x1a\x1cgoogle/protobuf/struct.proto\"'\n" +
	"\x11ReadSecretRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xc0\x01\n" +
	"\x12ReadSecretResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1c\n" +
	"\trenewable\x18\x03 \x01(\bR\trenewable\x12%\n" +
	"\x0elease_duration\x18\x04 \x01(\x05R\rleaseDuration\x12+\n" +
	"\x04data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04data\"U\n" +
	"\x12WriteSecretRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"/\n" +
	"\x13WriteSecretResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x12ListSecretsRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\")\n" +
	"\x13ListSecretsResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys2\x88\x02\n" +
	"\rSecretService\x12O\n" +
	"\n" +
	"ReadSecret\x12\x1f.secret_proto.ReadSecretRequest\x1a .secret_proto.ReadSecretResponse\x12R\n" +
	"\vWriteSecret\x12 .secret_proto.WriteSecretRequest\x1a!.secret_proto.WriteSecretResponse\x12R\n" +
	"\vListSecrets\x12 .secret_proto.ListSecretsRequest\x1a!.secret_proto.ListSecretsResponseB\x1bZ\x19vault-gateway/proto/vaultb\x06proto3"

var (
	file_proto_vault_vault_proto_rawDescOnce sync.Once
	file_proto_vault_vault_proto_rawDescData []byte
)

func file_proto_vault_vault_proto_rawDescGZIP() []byte {
	file_proto_vault_vault_proto_rawDescOnce.Do(func() {
		file_proto_vault_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vault_vault_proto_rawDesc), len(file_proto_vault_vault_proto_rawDesc)))
	})
	return file_proto_vault_vault_proto_rawDescData
}

var file_proto_vault_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_vault_vault_proto_goTypes = []any{
	(*ReadSecretRequest)(nil),   // 0: secret_proto.ReadSecretRequest
	(*ReadSecretResponse)(nil),  // 1: secret_proto.ReadSecretResponse
	(*WriteSecretRequest)(nil),  // 2: secret_proto.WriteSecretRequest
	(*WriteSecretResponse)(nil), // 3: secret_proto.WriteSecretResponse
	(*ListSecretsRequest)(nil),  // 4: secret_proto.ListSecretsRequest
	(*ListSecretsResponse)(nil), // 5: secret_proto.ListSecretsResponse
	(*structpb.Struct)(nil),     // 6: google.protobuf.Struct
}
var file_proto_vault_vault_proto_depIdxs = []int32{
	6, // 0: secret_proto.ReadSecretResponse.data:type_name -> google.protobuf.Struct
	6, // 1: secret_proto.WriteSecretRequest.data:type_name -> google.protobuf.Struct
	0, // 2: secret_proto.SecretService.ReadSecret:input_type -> secret_proto.ReadSecretRequest
	2, // 3: secret_proto.SecretService.WriteSecret:input_type -> secret_proto.WriteSecretRequest
	4, // 4: secret_proto.SecretService.ListSecrets:input_type -> secret_proto.ListSecretsRequest
	1, // 5: secret_proto.SecretService.ReadSecret:output_type -> secret_proto.ReadSecretResponse
	3, // 6: secret_proto.SecretService.WriteSecret:output_type -> secret_proto.WriteSecretResponse
	5, // 7: secret_proto.SecretService.ListSecrets:output_type -> secret_proto.ListSecretsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_vault_vault_proto_init() }
func file_proto_vault_vault_proto_init() {
	if File_proto_vault_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vault_vault_proto_rawDesc), len(file_proto_vault_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vault_vault_proto_goTypes,
		DependencyIndexes: file_proto_vault_vault_proto_depIdxs,
		MessageInfos:      file_proto_vault_vault_proto_msgTypes,
	}.Build()
	File_proto_vault_vault_proto = out.File
	file_proto_vault_vault_proto_goTypes = nil
	file_proto_vault_vault_proto_depIdxs = nil
}
