// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/ipam/ipam.proto

package ipam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Prefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	SiteId        int64                  `protobuf:"varint,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	VlanId        int64                  `protobuf:"varint,5,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prefix) Reset() {
	*x = Prefix{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prefix) ProtoMessage() {}

func (x *Prefix) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prefix.ProtoReflect.Descriptor instead.
func (*Prefix) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{3}
}

func (x *Prefix) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Prefix) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Prefix) GetSiteId() int64 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *Prefix) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Prefix) GetVlanId() int64 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *Prefix) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Prefix) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrefixRequest) Reset() {
	*x = CreatePrefixRequest{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrefixRequest) ProtoMessage() {}

func (x *CreatePrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrefixRequest.ProtoReflect.Descriptor instead.
func (*CreatePrefixRequest) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePrefixRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *CreatePrefixRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *CreatePrefixRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListPrefixesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Prefix              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrefixesResponse) Reset() {
	*x = ListPrefixesResponse{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrefixesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrefixesResponse) ProtoMessage() {}

func (x *ListPrefixesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrefixesResponse.ProtoReflect.Descriptor instead.
func (*ListPrefixesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{5}
}

func (x *ListPrefixesResponse) GetResults() []*Prefix {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListPrefixesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type IPAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TenantId      int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddress) Reset() {
	*x = IPAddress{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddress) ProtoMessage() {}

func (x *IPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddress.ProtoReflect.Descriptor instead.
func (*IPAddress) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{6}
}

func (x *IPAddress) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IPAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IPAddress) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *IPAddress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IPAddress) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateIPAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIPAddressRequest) Reset() {
	*x = CreateIPAddressRequest{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIPAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIPAddressRequest) ProtoMessage() {}

func (x *CreateIPAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIPAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateIPAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{7}
}

func (x *CreateIPAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateIPAddressRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *CreateIPAddressRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListIPAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*IPAddress           `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPAddressesResponse) Reset() {
	*x = ListIPAddressesResponse{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPAddressesResponse) ProtoMessage() {}

func (x *ListIPAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPAddressesResponse.ProtoReflect.Descriptor instead.
func (*ListIPAddressesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{8}
}

func (x *ListIPAddressesResponse) GetResults() []*IPAddress {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListIPAddressesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VLAN struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vid           int32                  `protobuf:"varint,2,opt,name=vid,proto3" json:"vid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SiteId        int64                  `protobuf:"varint,4,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VLAN) Reset() {
	*x = VLAN{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VLAN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VLAN) ProtoMessage() {}

func (x *VLAN) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VLAN.ProtoReflect.Descriptor instead.
func (*VLAN) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{9}
}

func (x *VLAN) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VLAN) GetVid() int32 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *VLAN) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VLAN) GetSiteId() int64 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *VLAN) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateVLANRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vid           int32                  `protobuf:"varint,1,opt,name=vid,proto3" json:"vid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SiteId        int64                  `protobuf:"varint,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVLANRequest) Reset() {
	*x = CreateVLANRequest{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVLANRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVLANRequest) ProtoMessage() {}

func (x *CreateVLANRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVLANRequest.ProtoReflect.Descriptor instead.
func (*CreateVLANRequest) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{10}
}

func (x *CreateVLANRequest) GetVid() int32 {
	if x != nil {
		return x.Vid
	}
	return 0
}

func (x *CreateVLANRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVLANRequest) GetSiteId() int64 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type ListVLANsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*VLAN                `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVLANsResponse) Reset() {
	*x = ListVLANsResponse{}
	mi := &file_proto_ipam_ipam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVLANsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVLANsResponse) ProtoMessage() {}

func (x *ListVLANsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ipam_ipam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVLANsResponse.ProtoReflect.Descriptor instead.
func (*ListVLANsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ipam_ipam_proto_rawDescGZIP(), []int{11}
}

func (x *ListVLANsResponse) GetResults() []*VLAN {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListVLANsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_ipam_ipam_proto protoreflect.FileDescriptor

const file_proto_ipam_ipam_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ipam/ipam.proto\x12\n" +
	"ipam_proto\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb9\x01\n" +
	"\x06Prefix\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\x03R\x06siteId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\x03R\btenantId\x12\x17\n" +
	"\avlan_id\x18\x05 \x01(\x03R\x06vlanId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"b\n" +
	"\x13CreatePrefixRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"Z\n" +
	"\x14ListPrefixesResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.ipam_proto.PrefixR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x8c\x01\n" +
	"\tIPAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"g\n" +
	"\x16CreateIPAddressRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"`\n" +
	"\x17ListIPAddressesResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.ipam_proto.IPAddressR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"m\n" +
	"\x04VLAN\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03vid\x18\x02 \x01(\x05R\x03vid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\asite_id\x18\x04 \x01(\x03R\x06siteId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"R\n" +
	"\x11CreateVLANRequest\x12\x10\n" +
	"\x03vid\x18\x01 \x01(\x05R\x03vid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\x03R\x06siteId\"U\n" +
	"\x11ListVLANsResponse\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.ipam_proto.VLANR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xe5\a\n" +
	"\vIpamService\x12I\n" +
	"\fListPrefixes\x12\x17.ipam_proto.ListRequest\x1a .ipam_proto.ListPrefixesResponse\x127\n" +
	"\tGetPrefix\x12\x16.ipam_proto.GetRequest\x1a\x12.ipam_proto.Prefix\x12C\n" +
	"\fCreatePrefix\x12\x1f.ipam_proto.CreatePrefixRequest\x1a\x12.ipam_proto.Prefix\x126\n" +
	"\fUpdatePrefix\x12\x12.ipam_proto.Prefix\x1a\x12.ipam_proto.Prefix\x12B\n" +
	"\fDeletePrefix\x12\x16.ipam_proto.GetRequest\x1a\x1a.ipam_proto.DeleteResponse\x12O\n" +
	"\x0fListIPAddresses\x12\x17.ipam_proto.ListRequest\x1a#.ipam_proto.ListIPAddressesResponse\x12=\n" +
	"\fGetIPAddress\x12\x16.ipam_proto.GetRequest\x1a\x15.ipam_proto.IPAddress\x12L\n" +
	"\x0fCreateIPAddress\x12\".ipam_proto.CreateIPAddressRequest\x1a\x15.ipam_proto.IPAddress\x12?\n" +
	"\x0fUpdateIPAddress\x12\x15.ipam_proto.IPAddress\x1a\x15.ipam_proto.IPAddress\x12E\n" +
	"\x0fDeleteIPAddress\x12\x16.ipam_proto.GetRequest\x1a\x1a.ipam_proto.DeleteResponse\x12C\n" +
	"\tListVLANs\x12\x17.ipam_proto.ListRequest\x1a\x1d.ipam_proto.ListVLANsResponse\x123\n" +
	"\aGetVLAN\x12\x16.ipam_proto.GetRequest\x1a\x10.ipam_proto.VLAN\x12=\n" +
	"\n" +
	"CreateVLAN\x12\x1d.ipam_proto.CreateVLANRequest\x1a\x10.ipam_proto.VLAN\x120\n" +
	"\n" +
	"UpdateVLAN\x12\x10.ipam_proto.VLAN\x1a\x10.ipam_proto.VLAN\x12@\n" +
	"\n" +
	"DeleteVLAN\x12\x16.ipam_proto.GetRequest\x1a\x1a.ipam_proto.DeleteResponseB\x1bZ\x19netbox-gateway/proto/ipamb\x06proto3"

var (
	file_proto_ipam_ipam_proto_rawDescOnce sync.Once
	file_proto_ipam_ipam_proto_rawDescData []byte
)

func file_proto_ipam_ipam_proto_rawDescGZIP() []byte {
	file_proto_ipam_ipam_proto_rawDescOnce.Do(func() {
		file_proto_ipam_ipam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ipam_ipam_proto_rawDesc), len(file_proto_ipam_ipam_proto_rawDesc)))
	})
	return file_proto_ipam_ipam_proto_rawDescData
}

var file_proto_ipam_ipam_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_ipam_ipam_proto_goTypes = []any{
	(*GetRequest)(nil),              // 0: ipam_proto.GetRequest
	(*ListRequest)(nil),             // 1: ipam_proto.ListRequest
	(*DeleteResponse)(nil),          // 2: ipam_proto.DeleteResponse
	(*Prefix)(nil),                  // 3: ipam_proto.Prefix
	(*CreatePrefixRequest)(nil),     // 4: ipam_proto.CreatePrefixRequest
	(*ListPrefixesResponse)(nil),    // 5: ipam_proto.ListPrefixesResponse
	(*IPAddress)(nil),               // 6: ipam_proto.IPAddress
	(*CreateIPAddressRequest)(nil),  // 7: ipam_proto.CreateIPAddressRequest
	(*ListIPAddressesResponse)(nil), // 8: ipam_proto.ListIPAddressesResponse
	(*VLAN)(nil),                    // 9: ipam_proto.VLAN
	(*CreateVLANRequest)(nil),       // 10: ipam_proto.CreateVLANRequest
	(*ListVLANsResponse)(nil),       // 11: ipam_proto.ListVLANsResponse
}
var file_proto_ipam_ipam_proto_depIdxs = []int32{
	3,  // 0: ipam_proto.ListPrefixesResponse.results:type_name -> ipam_proto.Prefix
	6,  // 1: ipam_proto.ListIPAddressesResponse.results:type_name -> ipam_proto.IPAddress
	9,  // 2: ipam_proto.ListVLANsResponse.results:type_name -> ipam_proto.VLAN
	1,  // 3: ipam_proto.IpamService.ListPrefixes:input_type -> ipam_proto.ListRequest
	0,  // 4: ipam_proto.IpamService.GetPrefix:input_type -> ipam_proto.GetRequest
	4,  // 5: ipam_proto.IpamService.CreatePrefix:input_type -> ipam_proto.CreatePrefixRequest
	3,  // 6: ipam_proto.IpamService.UpdatePrefix:input_type -> ipam_proto.Prefix
	0,  // 7: ipam_proto.IpamService.DeletePrefix:input_type -> ipam_proto.GetRequest
	1,  // 8: ipam_proto.IpamService.ListIPAddresses:input_type -> ipam_proto.ListRequest
	0,  // 9: ipam_proto.IpamService.GetIPAddress:input_type -> ipam_proto.GetRequest
	7,  // 10: ipam_proto.IpamService.CreateIPAddress:input_type -> ipam_proto.CreateIPAddressRequest
	6,  // 11: ipam_proto.IpamService.UpdateIPAddress:input_type -> ipam_proto.IPAddress
	0,  // 12: ipam_proto.IpamService.DeleteIPAddress:input_type -> ipam_proto.GetRequest
	1,  // 13: ipam_proto.IpamService.ListVLANs:input_type -> ipam_proto.ListRequest
	0,  // 14: ipam_proto.IpamService.GetVLAN:input_type -> ipam_proto.GetRequest
	10, // 15: ipam_proto.IpamService.CreateVLAN:input_type -> ipam_proto.CreateVLANRequest
	9,  // 16: ipam_proto.IpamService.UpdateVLAN:input_type -> ipam_proto.VLAN
	0,  // 17: ipam_proto.IpamService.DeleteVLAN:input_type -> ipam_proto.GetRequest
	5,  // 18: ipam_proto.IpamService.ListPrefixes:output_type -> ipam_proto.ListPrefixesResponse
	3,  // 19: ipam_proto.IpamService.GetPrefix:output_type -> ipam_proto.Prefix
	3,  // 20: ipam_proto.IpamService.CreatePrefix:output_type -> ipam_proto.Prefix
	3,  // 21: ipam_proto.IpamService.UpdatePrefix:output_type -> ipam_proto.Prefix
	2,  // 22: ipam_proto.IpamService.DeletePrefix:output_type -> ipam_proto.DeleteResponse
	8,  // 23: ipam_proto.IpamService.ListIPAddresses:output_type -> ipam_proto.ListIPAddressesResponse
	6,  // 24: ipam_proto.IpamService.GetIPAddress:output_type -> ipam_proto.IPAddress
	6,  // 25: ipam_proto.IpamService.CreateIPAddress:output_type -> ipam_proto.IPAddress
	6,  // 26: ipam_proto.IpamService.UpdateIPAddress:output_type -> ipam_proto.IPAddress
	2,  // 27: ipam_proto.IpamService.DeleteIPAddress:output_type -> ipam_proto.DeleteResponse
	11, // 28: ipam_proto.IpamService.ListVLANs:output_type -> ipam_proto.ListVLANsResponse
	9,  // 29: ipam_proto.IpamService.GetVLAN:output_type -> ipam_proto.VLAN
	9,  // 30: ipam_proto.IpamService.CreateVLAN:output_type -> ipam_proto.VLAN
	9,  // 31: ipam_proto.IpamService.UpdateVLAN:output_type -> ipam_proto.VLAN
	2,  // 32: ipam_proto.IpamService.DeleteVLAN:output_type -> ipam_proto.DeleteResponse
	18, // [18:33] is the sub-list for method output_type
	3,  // [3:18] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ipam_ipam_proto_init() }
func file_proto_ipam_ipam_proto_init() {
	if File_proto_ipam_ipam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ipam_ipam_proto_rawDesc), len(file_proto_ipam_ipam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ipam_ipam_proto_goTypes,
		DependencyIndexes: file_proto_ipam_ipam_proto_depIdxs,
		MessageInfos:      file_proto_ipam_ipam_proto_msgTypes,
	}.Build()
	File_proto_ipam_ipam_proto = out.File
	file_proto_ipam_ipam_proto_goTypes = nil
	file_proto_ipam_ipam_proto_depIdxs = nil
}
