// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/organization/organization.proto

package organization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_organization_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_organization_organization_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_organization_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_organization_organization_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_organization_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_organization_organization_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_proto_organization_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_proto_organization_organization_proto_rawDescGZIP(), []int{3}
}

func (x *Tenant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tenant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_proto_organization_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_organization_organization_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateTenantRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Tenant              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_proto_organization_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_organization_organization_proto_rawDescGZIP(), []int{5}
}

func (x *ListTenantsResponse) GetResults() []*Tenant {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListTenantsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Site struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Site) Reset() {
	*x = Site{}
	mi := &file_proto_organization_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Site) ProtoMessage() {}

func (x *Site) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Site.ProtoReflect.Descriptor instead.
func (*Site) Descriptor() ([]byte, []int) {
	return file_proto_organization_organization_proto_rawDescGZIP(), []int{6}
}

func (x *Site) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Site) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Site) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Site) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Site) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSiteRequest) Reset() {
	*x = CreateSiteRequest{}
	mi := &file_proto_organization_organization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteRequest) ProtoMessage() {}

func (x *CreateSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_organization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteRequest.ProtoReflect.Descriptor instead.
func (*CreateSiteRequest) Descriptor() ([]byte, []int) {
	return file_proto_organization_organization_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSiteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSiteRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateSiteRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateSiteRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListSitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Site                `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSitesResponse) Reset() {
	*x = ListSitesResponse{}
	mi := &file_proto_organization_organization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSitesResponse) ProtoMessage() {}

func (x *ListSitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_organization_organization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSitesResponse.ProtoReflect.Descriptor instead.
func (*ListSitesResponse) Descriptor() ([]byte, []int) {
	return file_proto_organization_organization_proto_rawDescGZIP(), []int{8}
}

func (x *ListSitesResponse) GetResults() []*Site {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListSitesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_organization_organization_proto protoreflect.FileDescriptor

const file_proto_organization_organization_proto_rawDesc = "" +
	"\n" +
	"%proto/organization/organization.proto\x12\x12organization_proto\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"b\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"_\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"a\n" +
	"\x13ListTenantsResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.organization_proto.TenantR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"x\n" +
	"\x04Site\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"u\n" +
	"\x11CreateSiteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"]\n" +
	"\x11ListSitesResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.organization_proto.SiteR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xa5\x06\n" +
	"\x13OrganizationService\x12W\n" +
	"\vListTenants\x12\x1f.organization_proto.ListRequest\x1a'.organization_proto.ListTenantsResponse\x12G\n" +
	"\tGetTenant\x12\x1e.organization_proto.GetRequest\x1a\x1a.organization_proto.Tenant\x12S\n" +
	"\fCreateTenant\x12'.organization_proto.CreateTenantRequest\x1a\x1a.organization_proto.Tenant\x12F\n" +
	"\fUpdateTenant\x12\x1a.organization_proto.Tenant\x1a\x1a.organization_proto.Tenant\x12R\n" +
	"\fDeleteTenant\x12\x1e.organization_proto.GetRequest\x1a\".organization_proto.DeleteResponse\x12S\n" +
	"\tListSites\x12\x1f.organization_proto.ListRequest\x1a%.organization_proto.ListSitesResponse\x12C\n" +
	"\aGetSite\x12\x1e.organization_proto.GetRequest\x1a\x18.organization_proto.Site\x12M\n" +
	"\n" +
	"CreateSite\x12%.organization_proto.CreateSiteRequest\x1a\x18.organization_proto.Site\x12@\n" +
	"\n" +
	"UpdateSite\x12\x18.organization_proto.Site\x1a\x18.organization_proto.Site\x12P\n" +
	"\n" +
	"DeleteSite\x12\x1e.organization_proto.GetRequest\x1a\".organization_proto.DeleteResponseB#Z!netbox-gateway/proto/organizationb\x06proto3"

var (
	file_proto_organization_organization_proto_rawDescOnce sync.Once
	file_proto_organization_organization_proto_rawDescData []byte
)

func file_proto_organization_organization_proto_rawDescGZIP() []byte {
	file_proto_organization_organization_proto_rawDescOnce.Do(func() {
		file_proto_organization_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_organization_organization_proto_rawDesc), len(file_proto_organization_organization_proto_rawDesc)))
	})
	return file_proto_organization_organization_proto_rawDescData
}

var file_proto_organization_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_organization_organization_proto_goTypes = []any{
	(*GetRequest)(nil),          // 0: organization_proto.GetRequest
	(*ListRequest)(nil),         // 1: organization_proto.ListRequest
	(*DeleteResponse)(nil),      // 2: organization_proto.DeleteResponse
	(*Tenant)(nil),              // 3: organization_proto.Tenant
	(*CreateTenantRequest)(nil), // 4: organization_proto.CreateTenantRequest
	(*ListTenantsResponse)(nil), // 5: organization_proto.ListTenantsResponse
	(*Site)(nil),                // 6: organization_proto.Site
	(*CreateSiteRequest)(nil),   // 7: organization_proto.CreateSiteRequest
	(*ListSitesResponse)(nil),   // 8: organization_proto.ListSitesResponse
}
var file_proto_organization_organization_proto_depIdxs = []int32{
	3,  // 0: organization_proto.ListTenantsResponse.results:type_name -> organization_proto.Tenant
	6,  // 1: organization_proto.ListSitesResponse.results:type_name -> organization_proto.Site
	1,  // 2: organization_proto.OrganizationService.ListTenants:input_type -> organization_proto.ListRequest
	0,  // 3: organization_proto.OrganizationService.GetTenant:input_type -> organization_proto.GetRequest
	4,  // 4: organization_proto.OrganizationService.CreateTenant:input_type -> organization_proto.CreateTenantRequest
	3,  // 5: organization_proto.OrganizationService.UpdateTenant:input_type -> organization_proto.Tenant
	0,  // 6: organization_proto.OrganizationService.DeleteTenant:input_type -> organization_proto.GetRequest
	1,  // 7: organization_proto.OrganizationService.ListSites:input_type -> organization_proto.ListRequest
	0,  // 8: organization_proto.OrganizationService.GetSite:input_type -> organization_proto.GetRequest
	7,  // 9: organization_proto.OrganizationService.CreateSite:input_type -> organization_proto.CreateSiteRequest
	6,  // 10: organization_proto.OrganizationService.UpdateSite:input_type -> organization_proto.Site
	0,  // 11: organization_proto.OrganizationService.DeleteSite:input_type -> organization_proto.GetRequest
	5,  // 12: organization_proto.OrganizationService.ListTenants:output_type -> organization_proto.ListTenantsResponse
	3,  // 13: organization_proto.OrganizationService.GetTenant:output_type -> organization_proto.Tenant
	3,  // 14: organization_proto.OrganizationService.CreateTenant:output_type -> organization_proto.Tenant
	3,  // 15: organization_proto.OrganizationService.UpdateTenant:output_type -> organization_proto.Tenant
	2,  // 16: organization_proto.OrganizationService.DeleteTenant:output_type -> organization_proto.DeleteResponse
	8,  // 17: organization_proto.OrganizationService.ListSites:output_type -> organization_proto.ListSitesResponse
	6,  // 18: organization_proto.OrganizationService.GetSite:output_type -> organization_proto.Site
	6,  // 19: organization_proto.OrganizationService.CreateSite:output_type -> organization_proto.Site
	6,  // 20: organization_proto.OrganizationService.UpdateSite:output_type -> organization_proto.Site
	2,  // 21: organization_proto.OrganizationService.DeleteSite:output_type -> organization_proto.DeleteResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_organization_organization_proto_init() }
func file_proto_organization_organization_proto_init() {
	if File_proto_organization_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_organization_organization_proto_rawDesc), len(file_proto_organization_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_organization_organization_proto_goTypes,
		DependencyIndexes: file_proto_organization_organization_proto_depIdxs,
		MessageInfos:      file_proto_organization_organization_proto_msgTypes,
	}.Build()
	File_proto_organization_organization_proto = out.File
	file_proto_organization_organization_proto_goTypes = nil
	file_proto_organization_organization_proto_depIdxs = nil
}
