// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/dcim/dcim.proto

package dcim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_dcim_dcim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dcim_dcim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_dcim_dcim_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_dcim_dcim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dcim_dcim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_dcim_dcim_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_dcim_dcim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dcim_dcim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_dcim_dcim_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Rack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SiteId        int64                  `protobuf:"varint,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	UHeight       int32                  `protobuf:"varint,6,opt,name=u_height,json=uHeight,proto3" json:"u_height,omitempty"`
	Comments      string                 `protobuf:"bytes,7,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rack) Reset() {
	*x = Rack{}
	mi := &file_proto_dcim_dcim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rack) ProtoMessage() {}

func (x *Rack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dcim_dcim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rack.ProtoReflect.Descriptor instead.
func (*Rack) Descriptor() ([]byte, []int) {
	return file_proto_dcim_dcim_proto_rawDescGZIP(), []int{3}
}

func (x *Rack) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Rack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rack) GetSiteId() int64 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *Rack) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Rack) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Rack) GetUHeight() int32 {
	if x != nil {
		return x.UHeight
	}
	return 0
}

func (x *Rack) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

type CreateRackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SiteId        int64                  `protobuf:"varint,2,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	UHeight       int32                  `protobuf:"varint,4,opt,name=u_height,json=uHeight,proto3" json:"u_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRackRequest) Reset() {
	*x = CreateRackRequest{}
	mi := &file_proto_dcim_dcim_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRackRequest) ProtoMessage() {}

func (x *CreateRackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dcim_dcim_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRackRequest.ProtoReflect.Descriptor instead.
func (*CreateRackRequest) Descriptor() ([]byte, []int) {
	return file_proto_dcim_dcim_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRackRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRackRequest) GetSiteId() int64 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *CreateRackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRackRequest) GetUHeight() int32 {
	if x != nil {
		return x.UHeight
	}
	return 0
}

type ListRacksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Rack                `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRacksResponse) Reset() {
	*x = ListRacksResponse{}
	mi := &file_proto_dcim_dcim_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRacksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRacksResponse) ProtoMessage() {}

func (x *ListRacksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dcim_dcim_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRacksResponse.ProtoReflect.Descriptor instead.
func (*ListRacksResponse) Descriptor() ([]byte, []int) {
	return file_proto_dcim_dcim_proto_rawDescGZIP(), []int{5}
}

func (x *ListRacksResponse) GetResults() []*Rack {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListRacksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeviceTypeId  int64                  `protobuf:"varint,3,opt,name=device_type_id,json=deviceTypeId,proto3" json:"device_type_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	SiteId        int64                  `protobuf:"varint,5,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	RackId        int64                  `protobuf:"varint,6,opt,name=rack_id,json=rackId,proto3" json:"rack_id,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_dcim_dcim_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dcim_dcim_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_dcim_dcim_proto_rawDescGZIP(), []int{6}
}

func (x *Device) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetDeviceTypeId() int64 {
	if x != nil {
		return x.DeviceTypeId
	}
	return 0
}

func (x *Device) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *Device) GetSiteId() int64 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *Device) GetRackId() int64 {
	if x != nil {
		return x.RackId
	}
	return 0
}

func (x *Device) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DeviceTypeId  int64                  `protobuf:"varint,2,opt,name=device_type_id,json=deviceTypeId,proto3" json:"device_type_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	SiteId        int64                  `protobuf:"varint,4,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceRequest) Reset() {
	*x = CreateDeviceRequest{}
	mi := &file_proto_dcim_dcim_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceRequest) ProtoMessage() {}

func (x *CreateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dcim_dcim_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_dcim_dcim_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDeviceRequest) GetDeviceTypeId() int64 {
	if x != nil {
		return x.DeviceTypeId
	}
	return 0
}

func (x *CreateDeviceRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CreateDeviceRequest) GetSiteId() int64 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Device              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_dcim_dcim_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dcim_dcim_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_dcim_dcim_proto_rawDescGZIP(), []int{8}
}

func (x *ListDevicesResponse) GetResults() []*Device {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListDevicesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_dcim_dcim_proto protoreflect.FileDescriptor

const file_proto_dcim_dcim_proto_rawDesc = "" +
	"\n" +
	"\x15proto/dcim/dcim.proto\x12\n" +
	"dcim_proto\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xaf\x01\n" +
	"\x04Rack\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\x03R\x06siteId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\x03R\btenantId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x19\n" +
	"\bu_height\x18\x06 \x01(\x05R\auHeight\x12\x1a\n" +
	"\bcomments\x18\a \x01(\tR\bcomments\"s\n" +
	"\x11CreateRackRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\asite_id\x18\x02 \x01(\x03R\x06siteId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\bu_height\x18\x04 \x01(\x05R\auHeight\"U\n" +
	"\x11ListRacksResponse\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.dcim_proto.RackR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xb5\x01\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x0edevice_type_id\x18\x03 \x01(\x03R\fdeviceTypeId\x12\x17\n" +
	"\arole_id\x18\x04 \x01(\x03R\x06roleId\x12\x17\n" +
	"\asite_id\x18\x05 \x01(\x03R\x06siteId\x12\x17\n" +
	"\arack_id\x18\x06 \x01(\x03R\x06rackId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\x81\x01\n" +
	"\x13CreateDeviceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12$\n" +
	"\x0edevice_type_id\x18\x02 \x01(\x03R\fdeviceTypeId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x03R\x06roleId\x12\x17\n" +
	"\asite_id\x18\x04 \x01(\x03R\x06siteId\"Y\n" +
	"\x13ListDevicesResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.dcim_proto.DeviceR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xfd\x04\n" +
	"\vDcimService\x12C\n" +
	"\tListRacks\x12\x17.dcim_proto.ListRequest\x1a\x1d.dcim_proto.ListRacksResponse\x123\n" +
	"\aGetRack\x12\x16.dcim_proto.GetRequest\x1a\x10.dcim_proto.Rack\x12=\n" +
	"\n" +
	"CreateRack\x12\x1d.dcim_proto.CreateRackRequest\x1a\x10.dcim_proto.Rack\x120\n" +
	"\n" +
	"UpdateRack\x12\x10.dcim_proto.Rack\x1a\x10.dcim_proto.Rack\x12@\n" +
	"\n" +
	"DeleteRack\x12\x16.dcim_proto.GetRequest\x1a\x1a.dcim_proto.DeleteResponse\x12G\n" +
	"\vListDevices\x12\x17.dcim_proto.ListRequest\x1a\x1f.dcim_proto.ListDevicesResponse\x127\n" +
	"\tGetDevice\x12\x16.dcim_proto.GetRequest\x1a\x12.dcim_proto.Device\x12C\n" +
	"\fCreateDevice\x12\x1f.dcim_proto.CreateDeviceRequest\x1a\x12.dcim_proto.Device\x126\n" +
	"\fUpdateDevice\x12\x12.dcim_proto.Device\x1a\x12.dcim_proto.Device\x12B\n" +
	"\fDeleteDevice\x12\x16.dcim_proto.GetRequest\x1a\x1a.dcim_proto.DeleteResponseB\x1bZ\x19netbox-gateway/proto/dcimb\x06proto3"

var (
	file_proto_dcim_dcim_proto_rawDescOnce sync.Once
	file_proto_dcim_dcim_proto_rawDescData []byte
)

func file_proto_dcim_dcim_proto_rawDescGZIP() []byte {
	file_proto_dcim_dcim_proto_rawDescOnce.Do(func() {
		file_proto_dcim_dcim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dcim_dcim_proto_rawDesc), len(file_proto_dcim_dcim_proto_rawDesc)))
	})
	return file_proto_dcim_dcim_proto_rawDescData
}

var file_proto_dcim_dcim_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_dcim_dcim_proto_goTypes = []any{
	(*GetRequest)(nil),          // 0: dcim_proto.GetRequest
	(*ListRequest)(nil),         // 1: dcim_proto.ListRequest
	(*DeleteResponse)(nil),      // 2: dcim_proto.DeleteResponse
	(*Rack)(nil),                // 3: dcim_proto.Rack
	(*CreateRackRequest)(nil),   // 4: dcim_proto.CreateRackRequest
	(*ListRacksResponse)(nil),   // 5: dcim_proto.ListRacksResponse
	(*Device)(nil),              // 6: dcim_proto.Device
	(*CreateDeviceRequest)(nil), // 7: dcim_proto.CreateDeviceRequest
	(*ListDevicesResponse)(nil), // 8: dcim_proto.ListDevicesResponse
}
var file_proto_dcim_dcim_proto_depIdxs = []int32{
	3,  // 0: dcim_proto.ListRacksResponse.results:type_name -> dcim_proto.Rack
	6,  // 1: dcim_proto.ListDevicesResponse.results:type_name -> dcim_proto.Device
	1,  // 2: dcim_proto.DcimService.ListRacks:input_type -> dcim_proto.ListRequest
	0,  // 3: dcim_proto.DcimService.GetRack:input_type -> dcim_proto.GetRequest
	4,  // 4: dcim_proto.DcimService.CreateRack:input_type -> dcim_proto.CreateRackRequest
	3,  // 5: dcim_proto.DcimService.UpdateRack:input_type -> dcim_proto.Rack
	0,  // 6: dcim_proto.DcimService.DeleteRack:input_type -> dcim_proto.GetRequest
	1,  // 7: dcim_proto.DcimService.ListDevices:input_type -> dcim_proto.ListRequest
	0,  // 8: dcim_proto.DcimService.GetDevice:input_type -> dcim_proto.GetRequest
	7,  // 9: dcim_proto.DcimService.CreateDevice:input_type -> dcim_proto.CreateDeviceRequest
	6,  // 10: dcim_proto.DcimService.UpdateDevice:input_type -> dcim_proto.Device
	0,  // 11: dcim_proto.DcimService.DeleteDevice:input_type -> dcim_proto.GetRequest
	5,  // 12: dcim_proto.DcimService.ListRacks:output_type -> dcim_proto.ListRacksResponse
	3,  // 13: dcim_proto.DcimService.GetRack:output_type -> dcim_proto.Rack
	3,  // 14: dcim_proto.DcimService.CreateRack:output_type -> dcim_proto.Rack
	3,  // 15: dcim_proto.DcimService.UpdateRack:output_type -> dcim_proto.Rack
	2,  // 16: dcim_proto.DcimService.DeleteRack:output_type -> dcim_proto.DeleteResponse
	8,  // 17: dcim_proto.DcimService.ListDevices:output_type -> dcim_proto.ListDevicesResponse
	6,  // 18: dcim_proto.DcimService.GetDevice:output_type -> dcim_proto.Device
	6,  // 19: dcim_proto.DcimService.CreateDevice:output_type -> dcim_proto.Device
	6,  // 20: dcim_proto.DcimService.UpdateDevice:output_type -> dcim_proto.Device
	2,  // 21: dcim_proto.DcimService.DeleteDevice:output_type -> dcim_proto.DeleteResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_dcim_dcim_proto_init() }
func file_proto_dcim_dcim_proto_init() {
	if File_proto_dcim_dcim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dcim_dcim_proto_rawDesc), len(file_proto_dcim_dcim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dcim_dcim_proto_goTypes,
		DependencyIndexes: file_proto_dcim_dcim_proto_depIdxs,
		MessageInfos:      file_proto_dcim_dcim_proto_msgTypes,
	}.Build()
	File_proto_dcim_dcim_proto = out.File
	file_proto_dcim_dcim_proto_goTypes = nil
	file_proto_dcim_dcim_proto_depIdxs = nil
}
