// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/virtualization/virtualization.proto

package virtualization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtualization_virtualization_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtualization_virtualization_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtualization_virtualization_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Cluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeId        int64                  `protobuf:"varint,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	SiteId        int64                  `protobuf:"varint,4,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_proto_virtualization_virtualization_proto_rawDescGZIP(), []int{3}
}

func (x *Cluster) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *Cluster) GetSiteId() int64 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

type CreateClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeId        int64                  `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterRequest) Reset() {
	*x = CreateClusterRequest{}
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterRequest) ProtoMessage() {}

func (x *CreateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtualization_virtualization_proto_rawDescGZIP(), []int{4}
}

func (x *CreateClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClusterRequest) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

type ListClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Cluster             `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersResponse) Reset() {
	*x = ListClustersResponse{}
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResponse) ProtoMessage() {}

func (x *ListClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersResponse.ProtoReflect.Descriptor instead.
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtualization_virtualization_proto_rawDescGZIP(), []int{5}
}

func (x *ListClustersResponse) GetResults() []*Cluster {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListClustersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VirtualMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ClusterId     int64                  `protobuf:"varint,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Vcpus         int32                  `protobuf:"varint,6,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,7,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskGb        int32                  `protobuf:"varint,8,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachine) Reset() {
	*x = VirtualMachine{}
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachine) ProtoMessage() {}

func (x *VirtualMachine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachine.ProtoReflect.Descriptor instead.
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return file_proto_virtualization_virtualization_proto_rawDescGZIP(), []int{6}
}

func (x *VirtualMachine) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VirtualMachine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualMachine) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VirtualMachine) GetClusterId() int64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *VirtualMachine) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *VirtualMachine) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *VirtualMachine) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VirtualMachine) GetDiskGb() int32 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

type CreateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ClusterId     int64                  `protobuf:"varint,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtualization_virtualization_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVMRequest) GetClusterId() int64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *CreateVMRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*VirtualMachine      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtualization_virtualization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtualization_virtualization_proto_rawDescGZIP(), []int{8}
}

func (x *ListVMsResponse) GetResults() []*VirtualMachine {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListVMsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_virtualization_virtualization_proto protoreflect.FileDescriptor

const file_proto_virtualization_virtualization_proto_rawDesc = "" +
	"\n" +
	")proto/virtualization/virtualization.proto\x12\x14virtualization_proto\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"_\n" +
	"\aCluster\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\atype_id\x18\x03 \x01(\x03R\x06typeId\x12\x17\n" +
	"\asite_id\x18\x04 \x01(\x03R\x06siteId\"C\n" +
	"\x14CreateClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\x03R\x06typeId\"e\n" +
	"\x14ListClustersResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.virtualization_proto.ClusterR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xd4\x01\n" +
	"\x0eVirtualMachine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\x03R\tclusterId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\x03R\btenantId\x12\x14\n" +
	"\x05vcpus\x18\x06 \x01(\x05R\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\a \x01(\x05R\bmemoryMb\x12\x17\n" +
	"\adisk_gb\x18\b \x01(\x05R\x06diskGb\"\\\n" +
	"\x0fCreateVMRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\x03R\tclusterId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"g\n" +
	"\x0fListVMsResponse\x12>\n" +
	"\aresults\x18\x01 \x03(\v2$.virtualization_proto.VirtualMachineR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xb0\a\n" +
	"\x15VirtualizationService\x12]\n" +
	"\fListClusters\x12!.virtualization_proto.ListRequest\x1a*.virtualization_proto.ListClustersResponse\x12M\n" +
	"\n" +
	"GetCluster\x12 .virtualization_proto.GetRequest\x1a\x1d.virtualization_proto.Cluster\x12Z\n" +
	"\rCreateCluster\x12*.virtualization_proto.CreateClusterRequest\x1a\x1d.virtualization_proto.Cluster\x12M\n" +
	"\rUpdateCluster\x12\x1d.virtualization_proto.Cluster\x1a\x1d.virtualization_proto.Cluster\x12W\n" +
	"\rDeleteCluster\x12 .virtualization_proto.GetRequest\x1a$.virtualization_proto.DeleteResponse\x12_\n" +
	"\x13ListVirtualMachines\x12!.virtualization_proto.ListRequest\x1a%.virtualization_proto.ListVMsResponse\x12[\n" +
	"\x11GetVirtualMachine\x12 .virtualization_proto.GetRequest\x1a$.virtualization_proto.VirtualMachine\x12c\n" +
	"\x14CreateVirtualMachine\x12%.virtualization_proto.CreateVMRequest\x1a$.virtualization_proto.VirtualMachine\x12b\n" +
	"\x14UpdateVirtualMachine\x12$.virtualization_proto.VirtualMachine\x1a$.virtualization_proto.VirtualMachine\x12^\n" +
	"\x14DeleteVirtualMachine\x12 .virtualization_proto.GetRequest\x1a$.virtualization_proto.DeleteResponseB%Z#netbox-gateway/proto/virtualizationb\x06proto3"

var (
	file_proto_virtualization_virtualization_proto_rawDescOnce sync.Once
	file_proto_virtualization_virtualization_proto_rawDescData []byte
)

func file_proto_virtualization_virtualization_proto_rawDescGZIP() []byte {
	file_proto_virtualization_virtualization_proto_rawDescOnce.Do(func() {
		file_proto_virtualization_virtualization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_virtualization_virtualization_proto_rawDesc), len(file_proto_virtualization_virtualization_proto_rawDesc)))
	})
	return file_proto_virtualization_virtualization_proto_rawDescData
}

var file_proto_virtualization_virtualization_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_virtualization_virtualization_proto_goTypes = []any{
	(*GetRequest)(nil),           // 0: virtualization_proto.GetRequest
	(*ListRequest)(nil),          // 1: virtualization_proto.ListRequest
	(*DeleteResponse)(nil),       // 2: virtualization_proto.DeleteResponse
	(*Cluster)(nil),              // 3: virtualization_proto.Cluster
	(*CreateClusterRequest)(nil), // 4: virtualization_proto.CreateClusterRequest
	(*ListClustersResponse)(nil), // 5: virtualization_proto.ListClustersResponse
	(*VirtualMachine)(nil),       // 6: virtualization_proto.VirtualMachine
	(*CreateVMRequest)(nil),      // 7: virtualization_proto.CreateVMRequest
	(*ListVMsResponse)(nil),      // 8: virtualization_proto.ListVMsResponse
}
var file_proto_virtualization_virtualization_proto_depIdxs = []int32{
	3,  // 0: virtualization_proto.ListClustersResponse.results:type_name -> virtualization_proto.Cluster
	6,  // 1: virtualization_proto.ListVMsResponse.results:type_name -> virtualization_proto.VirtualMachine
	1,  // 2: virtualization_proto.VirtualizationService.ListClusters:input_type -> virtualization_proto.ListRequest
	0,  // 3: virtualization_proto.VirtualizationService.GetCluster:input_type -> virtualization_proto.GetRequest
	4,  // 4: virtualization_proto.VirtualizationService.CreateCluster:input_type -> virtualization_proto.CreateClusterRequest
	3,  // 5: virtualization_proto.VirtualizationService.UpdateCluster:input_type -> virtualization_proto.Cluster
	0,  // 6: virtualization_proto.VirtualizationService.DeleteCluster:input_type -> virtualization_proto.GetRequest
	1,  // 7: virtualization_proto.VirtualizationService.ListVirtualMachines:input_type -> virtualization_proto.ListRequest
	0,  // 8: virtualization_proto.VirtualizationService.GetVirtualMachine:input_type -> virtualization_proto.GetRequest
	7,  // 9: virtualization_proto.VirtualizationService.CreateVirtualMachine:input_type -> virtualization_proto.CreateVMRequest
	6,  // 10: virtualization_proto.VirtualizationService.UpdateVirtualMachine:input_type -> virtualization_proto.VirtualMachine
	0,  // 11: virtualization_proto.VirtualizationService.DeleteVirtualMachine:input_type -> virtualization_proto.GetRequest
	5,  // 12: virtualization_proto.VirtualizationService.ListClusters:output_type -> virtualization_proto.ListClustersResponse
	3,  // 13: virtualization_proto.VirtualizationService.GetCluster:output_type -> virtualization_proto.Cluster
	3,  // 14: virtualization_proto.VirtualizationService.CreateCluster:output_type -> virtualization_proto.Cluster
	3,  // 15: virtualization_proto.VirtualizationService.UpdateCluster:output_type -> virtualization_proto.Cluster
	2,  // 16: virtualization_proto.VirtualizationService.DeleteCluster:output_type -> virtualization_proto.DeleteResponse
	8,  // 17: virtualization_proto.VirtualizationService.ListVirtualMachines:output_type -> virtualization_proto.ListVMsResponse
	6,  // 18: virtualization_proto.VirtualizationService.GetVirtualMachine:output_type -> virtualization_proto.VirtualMachine
	6,  // 19: virtualization_proto.VirtualizationService.CreateVirtualMachine:output_type -> virtualization_proto.VirtualMachine
	6,  // 20: virtualization_proto.VirtualizationService.UpdateVirtualMachine:output_type -> virtualization_proto.VirtualMachine
	2,  // 21: virtualization_proto.VirtualizationService.DeleteVirtualMachine:output_type -> virtualization_proto.DeleteResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_virtualization_virtualization_proto_init() }
func file_proto_virtualization_virtualization_proto_init() {
	if File_proto_virtualization_virtualization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_virtualization_virtualization_proto_rawDesc), len(file_proto_virtualization_virtualization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_virtualization_virtualization_proto_goTypes,
		DependencyIndexes: file_proto_virtualization_virtualization_proto_depIdxs,
		MessageInfos:      file_proto_virtualization_virtualization_proto_msgTypes,
	}.Build()
	File_proto_virtualization_virtualization_proto = out.File
	file_proto_virtualization_virtualization_proto_goTypes = nil
	file_proto_virtualization_virtualization_proto_depIdxs = nil
}
