// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/zabbix/zabbix.proto

package monitoring

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groupid       string                 `protobuf:"bytes,1,opt,name=groupid,proto3" json:"groupid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostGroup) Reset() {
	*x = HostGroup{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostGroup) ProtoMessage() {}

func (x *HostGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostGroup.ProtoReflect.Descriptor instead.
func (*HostGroup) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{0}
}

func (x *HostGroup) GetGroupid() string {
	if x != nil {
		return x.Groupid
	}
	return ""
}

func (x *HostGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostid        string                 `protobuf:"bytes,1,opt,name=hostid,proto3" json:"hostid,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{1}
}

func (x *Host) GetHostid() string {
	if x != nil {
		return x.Hostid
	}
	return ""
}

func (x *Host) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Host) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Itemid        string                 `protobuf:"bytes,1,opt,name=itemid,proto3" json:"itemid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Key_          string                 `protobuf:"bytes,3,opt,name=key_,json=key,proto3" json:"key_,omitempty"`
	Lastvalue     string                 `protobuf:"bytes,4,opt,name=lastvalue,proto3" json:"lastvalue,omitempty"`
	Lastclock     string                 `protobuf:"bytes,5,opt,name=lastclock,proto3" json:"lastclock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetItemid() string {
	if x != nil {
		return x.Itemid
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetKey_() string {
	if x != nil {
		return x.Key_
	}
	return ""
}

func (x *Item) GetLastvalue() string {
	if x != nil {
		return x.Lastvalue
	}
	return ""
}

func (x *Item) GetLastclock() string {
	if x != nil {
		return x.Lastclock
	}
	return ""
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triggerid     string                 `protobuf:"bytes,1,opt,name=triggerid,proto3" json:"triggerid,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Lastchange    string                 `protobuf:"bytes,4,opt,name=lastchange,proto3" json:"lastchange,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{3}
}

func (x *Alert) GetTriggerid() string {
	if x != nil {
		return x.Triggerid
	}
	return ""
}

func (x *Alert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Alert) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *Alert) GetLastchange() string {
	if x != nil {
		return x.Lastchange
	}
	return ""
}

func (x *Alert) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListHostGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostGroupsRequest) Reset() {
	*x = ListHostGroupsRequest{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostGroupsRequest) ProtoMessage() {}

func (x *ListHostGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListHostGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{4}
}

type ListHostGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*HostGroup           `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostGroupsResponse) Reset() {
	*x = ListHostGroupsResponse{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostGroupsResponse) ProtoMessage() {}

func (x *ListHostGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListHostGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{5}
}

func (x *ListHostGroupsResponse) GetGroups() []*HostGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ListHostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groupids      []string               `protobuf:"bytes,1,rep,name=groupids,proto3" json:"groupids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsRequest) Reset() {
	*x = ListHostsRequest{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsRequest) ProtoMessage() {}

func (x *ListHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsRequest.ProtoReflect.Descriptor instead.
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{6}
}

func (x *ListHostsRequest) GetGroupids() []string {
	if x != nil {
		return x.Groupids
	}
	return nil
}

type ListHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*Host                `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsResponse) Reset() {
	*x = ListHostsResponse{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsResponse) ProtoMessage() {}

func (x *ListHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsResponse.ProtoReflect.Descriptor instead.
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{7}
}

func (x *ListHostsResponse) GetHosts() []*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostids       []string               `protobuf:"bytes,1,rep,name=hostids,proto3" json:"hostids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{8}
}

func (x *ListItemsRequest) GetHostids() []string {
	if x != nil {
		return x.Hostids
	}
	return nil
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{9}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostids       []string               `protobuf:"bytes,1,rep,name=hostids,proto3" json:"hostids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsRequest) Reset() {
	*x = ListAlertsRequest{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsRequest) ProtoMessage() {}

func (x *ListAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{10}
}

func (x *ListAlertsRequest) GetHostids() []string {
	if x != nil {
		return x.Hostids
	}
	return nil
}

type ListAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zabbix_zabbix_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_proto_zabbix_zabbix_proto_rawDescGZIP(), []int{11}
}

func (x *ListAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_proto_zabbix_zabbix_proto protoreflect.FileDescriptor

const file_proto_zabbix_zabbix_proto_rawDesc = "" +
	"\n" +
	"\x19proto/zabbix/zabbix.proto\x12\x10monitoring_proto\"9\n" +
	"\tHostGroup\x12\x18\n" +
	"\agroupid\x18\x01 \x01(\tR\agroupid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"F\n" +
	"\x04Host\x12\x16\n" +
	"\x06hostid\x18\x01 \x01(\tR\x06hostid\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x81\x01\n" +
	"\x04Item\x12\x16\n" +
	"\x06itemid\x18\x01 \x01(\tR\x06itemid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x11\n" +
	"\x04key_\x18\x03 \x01(\tR\x03key\x12\x1c\n" +
	"\tlastvalue\x18\x04 \x01(\tR\tlastvalue\x12\x1c\n" +
	"\tlastclock\x18\x05 \x01(\tR\tlastclock\"\x99\x01\n" +
	"\x05Alert\x12\x1c\n" +
	"\ttriggerid\x18\x01 \x01(\tR\ttriggerid\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12\x1e\n" +
	"\n" +
	"lastchange\x18\x04 \x01(\tR\n" +
	"lastchange\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\"\x17\n" +
	"\x15ListHostGroupsRequest\"M\n" +
	"\x16ListHostGroupsResponse\x123\n" +
	"\x06groups\x18\x01 \x03(\v2\x1b.monitoring_proto.HostGroupR\x06groups\".\n" +
	"\x10ListHostsRequest\x12\x1a\n" +
	"\bgroupids\x18\x01 \x03(\tR\bgroupids\"A\n" +
	"\x11ListHostsResponse\x12,\n" +
	"\x05hosts\x18\x01 \x03(\v2\x16.monitoring_proto.HostR\x05hosts\",\n" +
	"\x10ListItemsRequest\x12\x18\n" +
	"\ahostids\x18\x01 \x03(\tR\ahostids\"A\n" +
	"\x11ListItemsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.monitoring_proto.ItemR\x05items\"-\n" +
	"\x11ListAlertsRequest\x12\x18\n" +
	"\ahostids\x18\x01 \x03(\tR\ahostids\"E\n" +
	"\x12ListAlertsResponse\x12/\n" +
	"\x06alerts\x18\x01 \x03(\v2\x17.monitoring_proto.AlertR\x06alerts2\xfd\x02\n" +
	"\x11MonitoringService\x12c\n" +
	"\x0eListHostGroups\x12'.monitoring_proto.ListHostGroupsRequest\x1a(.monitoring_proto.ListHostGroupsResponse\x12T\n" +
	"\tListHosts\x12\".monitoring_proto.ListHostsRequest\x1a#.monitoring_proto.ListHostsResponse\x12T\n" +
	"\tListItems\x12\".monitoring_proto.ListItemsRequest\x1a#.monitoring_proto.ListItemsResponse\x12W\n" +
	"\n" +
	"ListAlerts\x12#.monitoring_proto.ListAlertsRequest\x1a$.monitoring_proto.ListAlertsResponseB!Z\x1fzabbix-gateway/proto/monitoringb\x06proto3"

var (
	file_proto_zabbix_zabbix_proto_rawDescOnce sync.Once
	file_proto_zabbix_zabbix_proto_rawDescData []byte
)

func file_proto_zabbix_zabbix_proto_rawDescGZIP() []byte {
	file_proto_zabbix_zabbix_proto_rawDescOnce.Do(func() {
		file_proto_zabbix_zabbix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_zabbix_zabbix_proto_rawDesc), len(file_proto_zabbix_zabbix_proto_rawDesc)))
	})
	return file_proto_zabbix_zabbix_proto_rawDescData
}

var file_proto_zabbix_zabbix_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_zabbix_zabbix_proto_goTypes = []any{
	(*HostGroup)(nil),              // 0: monitoring_proto.HostGroup
	(*Host)(nil),                   // 1: monitoring_proto.Host
	(*Item)(nil),                   // 2: monitoring_proto.Item
	(*Alert)(nil),                  // 3: monitoring_proto.Alert
	(*ListHostGroupsRequest)(nil),  // 4: monitoring_proto.ListHostGroupsRequest
	(*ListHostGroupsResponse)(nil), // 5: monitoring_proto.ListHostGroupsResponse
	(*ListHostsRequest)(nil),       // 6: monitoring_proto.ListHostsRequest
	(*ListHostsResponse)(nil),      // 7: monitoring_proto.ListHostsResponse
	(*ListItemsRequest)(nil),       // 8: monitoring_proto.ListItemsRequest
	(*ListItemsResponse)(nil),      // 9: monitoring_proto.ListItemsResponse
	(*ListAlertsRequest)(nil),      // 10: monitoring_proto.ListAlertsRequest
	(*ListAlertsResponse)(nil),     // 11: monitoring_proto.ListAlertsResponse
}
var file_proto_zabbix_zabbix_proto_depIdxs = []int32{
	0,  // 0: monitoring_proto.ListHostGroupsResponse.groups:type_name -> monitoring_proto.HostGroup
	1,  // 1: monitoring_proto.ListHostsResponse.hosts:type_name -> monitoring_proto.Host
	2,  // 2: monitoring_proto.ListItemsResponse.items:type_name -> monitoring_proto.Item
	3,  // 3: monitoring_proto.ListAlertsResponse.alerts:type_name -> monitoring_proto.Alert
	4,  // 4: monitoring_proto.MonitoringService.ListHostGroups:input_type -> monitoring_proto.ListHostGroupsRequest
	6,  // 5: monitoring_proto.MonitoringService.ListHosts:input_type -> monitoring_proto.ListHostsRequest
	8,  // 6: monitoring_proto.MonitoringService.ListItems:input_type -> monitoring_proto.ListItemsRequest
	10, // 7: monitoring_proto.MonitoringService.ListAlerts:input_type -> monitoring_proto.ListAlertsRequest
	5,  // 8: monitoring_proto.MonitoringService.ListHostGroups:output_type -> monitoring_proto.ListHostGroupsResponse
	7,  // 9: monitoring_proto.MonitoringService.ListHosts:output_type -> monitoring_proto.ListHostsResponse
	9,  // 10: monitoring_proto.MonitoringService.ListItems:output_type -> monitoring_proto.ListItemsResponse
	11, // 11: monitoring_proto.MonitoringService.ListAlerts:output_type -> monitoring_proto.ListAlertsResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_zabbix_zabbix_proto_init() }
func file_proto_zabbix_zabbix_proto_init() {
	if File_proto_zabbix_zabbix_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_zabbix_zabbix_proto_rawDesc), len(file_proto_zabbix_zabbix_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_zabbix_zabbix_proto_goTypes,
		DependencyIndexes: file_proto_zabbix_zabbix_proto_depIdxs,
		MessageInfos:      file_proto_zabbix_zabbix_proto_msgTypes,
	}.Build()
	File_proto_zabbix_zabbix_proto = out.File
	file_proto_zabbix_zabbix_proto_goTypes = nil
	file_proto_zabbix_zabbix_proto_depIdxs = nil
}
